"""Tests for the F6 graph emitter (emit_lua_graph).

Tests verify the binding-surface LFR shape — the exact engine.* calls and
their order — for the common cases defined in docs/design/GRAPH_EMITTER.md.
"""

from __future__ import annotations

from fml_parser.emit_lua import emit_lua_graph
from fml_parser.models import FMLEntity, Floor, Script, Trigger


# ─── Helpers ─────────────────────────────────────────────────────────────────


def make_floor(entities: list[FMLEntity], **floor_props) -> Floor:
    """Construct a minimal Floor from a list of entities."""
    f = Floor(name="Test Floor", properties=floor_props)
    for ent in entities:
        f += ent
    return f


def make_entity(
    eid: str,
    name: str,
    kind: str,
    properties: dict | None = None,
    triggers: list[Trigger] | None = None,
    kind_chain: list[str] | None = None,
) -> FMLEntity:
    return FMLEntity(
        id=eid,
        name=name,
        kind=kind,
        properties=properties or {},
        triggers=triggers or [],
        kind_chain=kind_chain or [kind],
    )


# ─── Test (a): two rooms + item + player ─────────────────────────────────────


def test_tiny_floor_shape():
    """Two rooms connected by exits, an item in room1, a player in room1."""
    room1 = make_entity(
        "entry_hall", "Entry Hall", "room",
        properties={"exits": {"north": "inner_sanctum"}},
    )
    room2 = make_entity(
        "inner_sanctum", "Inner Sanctum", "room",
        properties={"exits": {"south": "entry_hall"}},
    )
    sword = make_entity(
        "old_sword", "Old Sword", "item",
        properties={"location": "entry_hall", "weight": 3},
    )
    player = make_entity(
        "hero", "Hero", "player",
        properties={"location": "entry_hall"},
        kind_chain=["player"],
    )

    floor = make_floor([room1, room2, sword, player])
    out = emit_lua_graph(floor, source_path="test.md")

    # Header
    assert "-- Generated by fml-parser (graph emitter)" in out
    assert "-- fml-source-hash:" in out

    # map relation defined once
    assert 'engine.define_relation("map"' in out
    assert "symmetric = true" in out

    # All four create_node calls present
    assert 'local n_entry_hall = engine.create_node(' in out
    assert 'local n_inner_sanctum = engine.create_node(' in out
    assert 'local n_old_sword = engine.create_node(' in out
    assert 'local n_hero = engine.create_node(' in out

    # name props
    assert '"Entry Hall"' in out
    assert '"Inner Sanctum"' in out

    # scalar prop for weight emitted
    assert "weight = 3" in out

    # location is NOT emitted inline in create_node
    # (check that 'location' only appears as relate, not as a prop in create_node)
    create_node_line = next(
        ln for ln in out.splitlines() if "n_old_sword = engine.create_node" in ln
    )
    assert "location" not in create_node_line

    # Containment: sword in entry_hall
    assert 'engine.relate("in", n_old_sword, n_entry_hall)' in out
    # Player containment
    assert 'engine.relate("in", n_hero, n_entry_hall)' in out

    # Exits (map relations)
    assert 'engine.relate("map", n_entry_hall, n_inner_sanctum)' in out
    assert 'engine.relate("map", n_inner_sanctum, n_entry_hall)' in out

    # Start actor
    assert "engine.set_start_actor(n_hero)" in out


def test_tiny_floor_order():
    """define_relation must appear before create_node, which must appear before relate."""
    room1 = make_entity(
        "cave", "Cave", "room",
        properties={"exits": {"east": "forest"}},
    )
    room2 = make_entity("forest", "Forest", "room")
    player = make_entity(
        "wanderer", "Wanderer", "player",
        kind_chain=["player"],
    )

    out = emit_lua_graph(make_floor([room1, room2, player]))
    lines = out.splitlines()

    def line_index(fragment: str) -> int:
        for i, ln in enumerate(lines):
            if fragment in ln:
                return i
        return -1

    define_rel_idx = line_index("define_relation")
    create_cave_idx = line_index("n_cave = engine.create_node")
    relate_map_idx = line_index('relate("map"')
    set_actor_idx = line_index("set_start_actor")

    assert define_rel_idx != -1
    assert create_cave_idx != -1
    assert relate_map_idx != -1
    assert set_actor_idx != -1

    assert define_rel_idx < create_cave_idx, "define_relation must precede create_node"
    assert create_cave_idx < relate_map_idx, "create_node must precede relate"
    assert relate_map_idx < set_actor_idx, "relate must precede set_start_actor"


# ─── Test (b): emergent verb (target_rel, no triggers) ───────────────────────


def test_emergent_verb():
    """A verb with target_rel and no triggers emits define_verb without stages."""
    lock_verb = make_entity(
        "lock", "Lock", "verb",
        properties={"noun": "required", "target_rel": "in"},
    )
    floor = make_floor([lock_verb])
    out = emit_lua_graph(floor)

    assert 'engine.define_verb({' in out
    assert 'name = "lock"' in out
    assert 'target_rel = "in"' in out
    # No stages block when there are no lua triggers.
    assert "stages" not in out


# ─── Test (c): verb with lua-script trigger ───────────────────────────────────


def test_verb_with_lua_stage():
    """A verb with a lua script trigger emits a stages = { on = function(ctx) ... } block."""
    script = Script(language="lua", source="engine.output(\"Hello\")")
    trigger = Trigger(name="On Use", script=script)
    examine_verb = make_entity(
        "examine", "Examine", "verb",
        properties={"noun": "optional"},
        triggers=[trigger],
    )
    floor = make_floor([examine_verb])
    out = emit_lua_graph(floor)

    assert 'engine.define_verb({' in out
    assert 'name = "examine"' in out
    assert "stages = {" in out
    assert "on = function(ctx)" in out
    assert 'engine.output("Hello")' in out
    assert "end," in out


# ─── Test (d): built-in verbs are skipped ─────────────────────────────────────


def test_builtin_verbs_skipped():
    """take, drop, put-in, go must not appear in define_verb calls."""
    builtins = [
        make_entity("take", "Take", "verb"),
        make_entity("drop", "Drop", "verb"),
        make_entity("put_in", "Put In", "verb"),
        make_entity("go", "Go", "verb"),
    ]
    custom = make_entity("open", "Open", "verb", properties={"noun": "required"})
    floor = make_floor(builtins + [custom])
    out = emit_lua_graph(floor)

    assert 'name = "open"' in out

    # Verify no define_verb for the built-in names.
    for builtin_name in ("take", "drop", "put_in", "go"):
        # Check that the name literal doesn't appear as a define_verb name field.
        assert f'name = "{builtin_name}"' not in out, (
            f"Built-in verb '{builtin_name}' should not be emitted"
        )


# ─── Test (e): determinism ────────────────────────────────────────────────────


def test_determinism():
    """Same floor emitted twice produces bit-identical output."""
    room = make_entity(
        "dungeon", "Dungeon", "room",
        properties={"exits": {"up": "surface"}, "dark": True},
    )
    surface = make_entity("surface", "Surface", "room")
    npc = make_entity(
        "guard", "Guard", "npc",
        properties={"location": "dungeon", "hp": 10},
    )
    script = Script(language="luau", source="ctx.actor.hp = ctx.actor.hp - 1")
    trigger = Trigger(name="On Attack", script=script)
    attack_verb = make_entity(
        "attack", "Attack", "verb",
        properties={"noun": "required", "scope": "touch"},
        triggers=[trigger],
    )
    player = make_entity(
        "adventurer", "Adventurer", "player",
        properties={"location": "dungeon"},
        kind_chain=["player"],
    )

    floor = make_floor([room, surface, npc, attack_verb, player])

    out1 = emit_lua_graph(floor)
    out2 = emit_lua_graph(floor)

    assert out1 == out2, "Two emissions of the same floor must be identical"


# ─── Test: start actor from floor property ───────────────────────────────────


def test_start_actor_from_floor_property():
    """Floor 'start' property naming an entity id selects the start actor."""
    room = make_entity("hall", "Hall", "room")
    entity = make_entity("the_player", "The Player", "actor")
    floor = make_floor([room, entity], start="the_player")
    out = emit_lua_graph(floor)
    assert "engine.set_start_actor(n_the_player)" in out


def test_no_start_actor_emits_comment():
    """When no player can be determined, a comment is emitted."""
    room = make_entity("hall", "Hall", "room")
    floor = make_floor([room])
    out = emit_lua_graph(floor)
    assert "engine.set_start_actor" not in out or "-- engine.set_start_actor" in out


# ─── Test: non-lua trigger body produces warning comment ─────────────────────


def test_non_lua_trigger_warning():
    """A trigger without a lua script emits a WARNING comment, not code."""
    from fml_parser.models import ActionLine, OutputLine

    trigger = Trigger(
        name="On Use",
        body=[OutputLine(template="You use the thing.")],
    )
    use_verb = make_entity(
        "use", "Use", "verb",
        properties={"noun": "required"},
        triggers=[trigger],
    )
    floor = make_floor([use_verb])
    out = emit_lua_graph(floor)

    assert "WARNING" in out
    assert "non-script FML body" in out
    # The body content must NOT be emitted as Lua.
    assert "You use the thing" not in out
